### ISSUE TITLE
Publishing a Global Body Plan

### ISSUE THREAD

**Issue by AndrewZheng-1011** [robomechanics/quad-sdk#308]
Hello, 
I am currently working on integrating an offline (not realtime) global planner where given the double integrator dynamics, I get state and control input trajectories from a different software (Matlab). As an intermediate step, I want to execute the state and control trajectories into this framework, and therefore, I thought it would be a nice to have a framework where I can more or less test the global planning frameworks easily. My initial plan is to write a script to publish a simple global plan (some hardcoded sequence of state and action vectors) and see the execution of the resulting local planner and robot driver.

From what I have understand of the code, this seems doable with the existing framework that you guys currently have. I believe my easiest option is to simply inherit the global_body_plan class and create some form of publisher (and potentially subscriber for easier modifiability of state and action sequences) to execute a FullState plan.

I saw in Issue #189 that there was a comment to inject a simple global plan, but I wasn't able to decipher if that was along the same idea of what I want to implement. Could you give me some insights if my current idea is possible or if there was an already existing framework that I could simply use instead?

**Comment by jcnorby** [comment]
Yep, super doable! I've done stuff like this a bunch for testing although never got around to releasing a convenient API for it so it'll take some (hopefully minimal) legwork to implement. This is also a bit ironic as the very first implementation of the global planner was written in C++ but interfaced through MATLAB (although that code would be more work to revive than would be worth).

I think you have the gist of it - you just need to publish a message of type GlobalPlan.msg with the correct data in order to track it. If you want to do this from MATLAB you could just load the data directly into a message of that type without trying to port the GlobalBodyPlan class as well. If you were just looking to modify what is there then there are a few options:

- Define state/action sequences by hand and use GlobalBodyPlan::loadPlanData() and convertToMsg() (some poorly organized version of this can be seen [here](https://github.com/robomechanics/quad-sdk/blob/ed850901f641918c3be023f60b36f34b37c86757/global_body_planner/src/fast_global_motion_planner.cpp#L302)
- Load data directly into a GlobalBodyPlan, in particular youll need vectors of time, state, and GRFs (basically the outputs of the loadPlanData() function) then use convertToMsg() to get the message that you would publish

Hope this helps!
