### ISSUE TITLE
For different Robot, what params should i watch out?

### ISSUE THREAD

**Issue by Czworldy** [robomechanics/quad-sdk#390]
My question is that if i load a **large mass robot** (more than 50kg) which the size and the mass of this robot is totally different from the `a1` and `spirit` what params should i watch out?

And what i did has been written in my late issue #387 , here i try to load a large size quadruped robot, i can let it stand up but as long as i start the local mpc planner i.e. `reference=twist` it will get very strange plan, before i send the control velocity cmd.

Thanks a lot!
Best

**Comment by ardalantj** [comment]
@Czworldy You would need to re-generate the dynamics with the updated mass and inertia properties. This is done in Matlab using Casadi inside nmpc_controller/scripts folder. By updating those parameters and running the script, casadi will automatically generate some files that the NMPC controller uses for the optimization. You have to make sure that you are using the updated dynamics and not the default.

**Comment by ardalantj** [comment]
These are the main ones, you may also want to play with kp, kd gains for the joints and standing height which can be different depending on your robot.

**Comment by nanbwrn** [comment]
hi,@Czworldy

I loaded the Unitree B1 robot in Gazebo, and I made modifications based on the code for controlling the A1. However, when I run the command to make the robot stand, the B1 robot only stands halfway. The size of Unitree B1 is much larger than that of A1 or Go1. I would like to ask how you achieve standing for larger-sized robots. Is the incomplete standing situation due to the larger size of B1?


After running the stand command, it looks like this.


![88e229d53686c19bc8821261aa75bf0](https://github.com/robomechanics/quad-sdk/assets/132453617/80e776a9-5c33-46a8-84ab-4a4e5a5ba70d)

**Comment by nanbwrn** [comment]
hi,@Czworldy 

I loaded the Unitree B1 robot in Gazebo, and I made modifications based on the code for controlling the A1. However, when I run the command to make the robot stand, the B1 robot only stands halfway. Then the robot remained stationary.The size of Unitree B1 is much larger than that of A1 or Go1. I would like to ask how you achieve standing for larger-sized robots. Is the incomplete standing situation due to the larger size of B1?

After running the stand command, it looks like this.
![024b6644079bfc334c232ab431bfdc7](https://github.com/robomechanics/quad-sdk/assets/132453617/f58f8359-45da-43e9-9045-1335048a2b1a)
![1f7203c28b79baa8d31aad90f702f48](https://github.com/robomechanics/quad-sdk/assets/132453617/80acce21-eab1-4c5a-879e-da0f39acd358)
