### ISSUE TITLE
focus on nmpc_controller script parameters for matlab and casadi

### ISSUE THREAD

**Issue by elpimous** [robomechanics/quad-sdk#393]
can you confirm the following params : 

* parameter.physics.gravitational_constant=9.81; % Gravity  % ok
* parameter.physics.sim2real_scale_factor=**1**; % your real robot (**what real values should we use here ? Spirit has other ones**)
* parameter.physics.mass_body_body=parameter.physics.sim2real_scale_factor***5.7**; % (**full weight - 4 * mass_body_leg**)
* parameter.physics.mass_body_leg=**1.935**; % Each leg weight (**what are leg parts ? from foot to hip motor included, without shoulder(ABAD) ?**)
* parameter.physics.hip_offset=[**0.190; 0.0575; 0**]; % Absolute hip offset from body COM of robot (**Absolute hip offset = x,y,z center of hip, correct ?**)
* parameter.physics.inertia_body=parameter.physics.sim2real_scale_factor*...
     [**0.02, 0.00194, 0.0;
     0.0158533, -0.0001332, -0.0002403;
     0.04168, 0.000015299, 0.04742**]; % Body inertia of robot (**trunk_com_x...trunk_ixx...trunk_iyy...**)
* parameter.name = "ylo2"; % your robot name

**Comment by yanhaoy** [comment]
sim2real_scale_factor is used to handle the mass difference between Ghost Robotics' original spirit40 SDF file and the actual mass of our robot. The original SDF recorded a weight of 5.75kg and a total mass of 11.6620kg. But we weighed our robot and found its mass to be 13.3 kg. We assume that all extra mass is added to the body, so we add this scaling factor to the body mass and body inertia. Note that the SDF files in this repository have been matched to the actual mass of the robot. If you have actual measurements of the robot's physics, you can just set this factor to 1.

For the leg mass calculation, we only summed the link mass of the legs since all of the Spirit 40's motors are on the side near the body.

Hip offset is the vector in the body frame from the body COM to the first leg motor.

The body inertia should be symmetrical and the order is [Ixx, Ixy, Ixz; Iyx, Iyy, Iyz; Izx, Izy, Izz], where Ixy = Iyx, Ixz=Izx, Iyz=Izy.
